content:
  - id: configuracion
    label: "Diseño y Temporadas"
    type: file
    path: public/ajustes.json
    fields:
      - {id: nombre_tienda, label: "Nombre de la Vitrina", type: string}
      - {id: banner_inicial, label: "Imagen de Portada (URL)", type: string}
      - {id: mensaje_bienvenida, label: "Texto de Bienvenida", type: string}
      - {id: color_principal, label: "Color de Barra (Hex)", type: string}
      - {id: color_fondo, label: "Color de Fondo (Hex)", type: string}
      - {id: aviso_alerta, label: "Barra de Anuncios", type: string}

  - id: inventario
    label: "Catálogo de Productos"
    type: file
    path: public/productos.json
    fields:
      - id: lista_productos
        label: "Lista de Herramientas"
        type: list
        fields:
          - {id: id, label: "ID Único (Número)", type: number}
          - {id: nombre, label: "Nombre del Producto", type: string}
          - {id: precio, label: "Precio (Solo Números)", type: number}
          - {id: sku, label: "Código SKU", type: string}
          - {id: descripcion, label: "Descripción", type: string}
          - {id: imagen, label: "Ruta de la Imagen", type: string}
