backend:
  name: github
  repo: laloh-g/tecnosolar 
  branch: main

media_folder: "public/media"
public_folder: "/media"

collections:
  - name: "ajustes"
    label: "Diseño y Temporadas"
    files:
      - file: "public/ajustes.json"
        label: "Ajustes de la Tienda"
        name: "ajustes_tienda"
        fields:
          - {label: "Nombre de la Vitrina", name: "nombre_tienda", widget: "string"}
          - {label: "Imagen de Portada (URL)", name: "banner_inicial", widget: "string"}
          - {label: "Texto de Bienvenida", name: "mensaje_bienvenida", widget: "string"}
          - {label: "Color de Barra (Hex)", name: "color_principal", widget: "string"}
          - {label: "Color de Fondo (Hex)", name: "color_fondo", widget: "string"}
          - {label: "Barra de Anuncios", name: "aviso_alerta", widget: "string"}

  - name: "productos"
    label: "Catálogo de Productos"
    folder: "public"
    filter: {field: "id", value: ""}
    extension: "json"
    format: "json"
    fields:
      - {label: "ID Único (Número)", name: "id", widget: "number", value_type: "int"}
      - {label: "Nombre del Producto", name: "nombre", widget: "string"}
      - {label: "Precio (Solo Números)", name: "precio", widget: "number", value_type: "int"}
      - {label: "Código SKU", name: "sku", widget: "string"}
      - {label: "Descripción", name: "descripcion", widget: "text"}
      - {label: "Ruta de la Imagen", name: "imagen", widget: "string"}
